eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  
# Management and Actuator Settings
management:
  tracing:
    sampling:
      probability: 1.0    # 100% of requests are traced (adjust in production, e.g., 0.1 for 10%)
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin server endpoint



    
